// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace Workshop.Calendar.Api
{
    public partial class Attendee
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("email")]
        public string Email { get; set; } = default!;
        [Required]
        [Column("name")]
        public string Name { get; set; } = default!;
        [Required]
        [Column("timeZone")]
        public string TimeZone { get; set; } = default!;
        [Column("bookingId")]
        public int? BookingId { get; set; }

        [ForeignKey(nameof(BookingId))]
        [InverseProperty("Attendee")]
        public virtual Booking? Booking { get; set; }
    }
}