// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NodaTime;

#nullable enable

namespace Workshop.Calendar.Api
{
    public partial class Availability
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("label")]
        public string? Label { get; set; }
        [Column("userId")]
        public int? UserId { get; set; }
        [Column("eventTypeId")]
        public int? EventTypeId { get; set; }
        [Column("days")]
        public int[]? Days { get; set; }
        [Column("startTime")]
        public int StartTime { get; set; }
        [Column("endTime")]
        public int EndTime { get; set; }
        [Column("date")]
        public LocalDate? Date { get; set; }

        [ForeignKey(nameof(EventTypeId))]
        [InverseProperty("Availability")]
        public virtual EventType? EventType { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Users.Availability))]
        public virtual Users? User { get; set; }
    }
}