// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace Workshop.Calendar.Api
{
    [Index(nameof(BookingId), Name = "DailyEventReference_bookingId_unique", IsUnique = true)]
    public partial class DailyEventReference
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("dailyurl")]
        public string Dailyurl { get; set; } = default!;
        [Required]
        [Column("dailytoken")]
        public string Dailytoken { get; set; } = default!;
        [Column("bookingId")]
        public int? BookingId { get; set; }

        [ForeignKey(nameof(BookingId))]
        [InverseProperty("DailyEventReference")]
        public virtual Booking? Booking { get; set; }
    }
}