// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace Workshop.Calendar.Api
{
    public partial class EventTypeCustomInput
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("eventTypeId")]
        public int EventTypeId { get; set; }
        [Required]
        [Column("label")]
        public string Label { get; set; } = default!;
        [Column("required")]
        public bool Required { get; set; }
        [Required]
        [Column("placeholder")]
        public string Placeholder { get; set; } = default!;

        [ForeignKey(nameof(EventTypeId))]
        [InverseProperty("EventTypeCustomInput")]
        public virtual EventType EventType { get; set; } = default!;
    }
}