// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace Workshop.Calendar.Api
{
    public partial class Membership
    {
        [Key]
        [Column("teamId")]
        public int TeamId { get; set; }
        [Key]
        [Column("userId")]
        public int UserId { get; set; }
        [Column("accepted")]
        public bool Accepted { get; set; }

        [ForeignKey(nameof(TeamId))]
        [InverseProperty("Membership")]
        public virtual Team Team { get; set; } = default!;
        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Users.Membership))]
        public virtual Users User { get; set; } = default!;
    }
}