// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace Workshop.Calendar.Api
{
    [Index(nameof(ExternalId), Name = "Payment.externalId_unique", IsUnique = true)]
    [Index(nameof(Uid), Name = "Payment.uid_unique", IsUnique = true)]
    public partial class Payment
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("uid")]
        public string Uid { get; set; } = default!;
        [Column("bookingId")]
        public int BookingId { get; set; }
        [Column("amount")]
        public int Amount { get; set; }
        [Column("fee")]
        public int Fee { get; set; }
        [Required]
        [Column("currency")]
        public string Currency { get; set; } = default!;
        [Column("success")]
        public bool Success { get; set; }
        [Column("refunded")]
        public bool Refunded { get; set; }
        [Required]
        [Column("data", TypeName = "jsonb")]
        public string Data { get; set; } = default!;
        [Required]
        [Column("externalId")]
        public string ExternalId { get; set; } = default!;

        [ForeignKey(nameof(BookingId))]
        [InverseProperty("Payment")]
        public virtual Booking Booking { get; set; } = default!;
    }
}