// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NodaTime;

#nullable enable

namespace Workshop.Calendar.Api
{
    public partial class ReminderMail
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("referenceId")]
        public int ReferenceId { get; set; }
        [Column("elapsedMinutes")]
        public int ElapsedMinutes { get; set; }
        [Column("createdAt", TypeName = "timestamp(3) without time zone")]
        public Instant CreatedAt { get; set; }
    }
}