// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NodaTime;

#nullable enable

namespace Workshop.Calendar.Api
{
    public partial class ResetPasswordRequest
    {
        [Key]
        [Column("id")]
        public string Id { get; set; } = default!;
        [Column("createdAt", TypeName = "timestamp(3) without time zone")]
        public Instant CreatedAt { get; set; }
        [Column("updatedAt", TypeName = "timestamp(3) without time zone")]
        public Instant UpdatedAt { get; set; }
        [Required]
        [Column("email")]
        public string Email { get; set; } = default!;
        [Column("expires", TypeName = "timestamp(3) without time zone")]
        public Instant Expires { get; set; }
    }
}