// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace Workshop.Calendar.Api
{
    public partial class Schedule
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("userId")]
        public int? UserId { get; set; }
        [Column("eventTypeId")]
        public int? EventTypeId { get; set; }
        [Column("title")]
        public string? Title { get; set; }
        [Column("freeBusyTimes", TypeName = "jsonb")]
        public string? FreeBusyTimes { get; set; }

        [ForeignKey(nameof(EventTypeId))]
        [InverseProperty("Schedule")]
        public virtual EventType? EventType { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Users.Schedule))]
        public virtual Users? User { get; set; }
    }
}