// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace Workshop.Calendar.Api
{
    public partial class SelectedCalendar
    {
        [Key]
        [Column("userId")]
        public int UserId { get; set; }
        [Key]
        [Column("integration")]
        public string Integration { get; set; } = default!;
        [Key]
        [Column("externalId")]
        public string ExternalId { get; set; } = default!;

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Users.SelectedCalendar))]
        public virtual Users User { get; set; } = default!;
    }
}