// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace Workshop.Calendar.Api
{
    [Index(nameof(Slug), Name = "Team.slug_unique", IsUnique = true)]
    public partial class Team
    {
        public Team()
        {
            EventType = new HashSet<EventType>();
            Membership = new HashSet<Membership>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("slug")]
        public string? Slug { get; set; }
        [Column("logo")]
        public string? Logo { get; set; }
        [Column("bio")]
        public string? Bio { get; set; }
        [Column("hideBranding")]
        public bool HideBranding { get; set; }

        [InverseProperty("Team")]
        public virtual ICollection<EventType> EventType { get; set; }
        [InverseProperty("Team")]
        public virtual ICollection<Membership> Membership { get; set; }
    }
}