// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NodaTime;

#nullable enable

namespace Workshop.Calendar.Api
{
    [Table("users")]
    [Index(nameof(Email), Name = "users.email_unique", IsUnique = true)]
    [Index(nameof(Username), Name = "users.username_unique", IsUnique = true)]
    public partial class Users
    {
        public Users()
        {
            Availability = new HashSet<Availability>();
            Booking = new HashSet<Booking>();
            Credential = new HashSet<Credential>();
            Membership = new HashSet<Membership>();
            Schedule = new HashSet<Schedule>();
            SelectedCalendar = new HashSet<SelectedCalendar>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("username")]
        public string? Username { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("email")]
        public string? Email { get; set; }
        [Column("emailVerified", TypeName = "timestamp(3) without time zone")]
        public Instant? EmailVerified { get; set; }
        [Column("password")]
        public string? Password { get; set; }
        [Column("bio")]
        public string? Bio { get; set; }
        [Column("avatar")]
        public string? Avatar { get; set; }
        [Required]
        [Column("timeZone")]
        public string TimeZone { get; set; } = default!;
        [Column("weekStart")]
        public string? WeekStart { get; set; }
        [Column("startTime")]
        public int StartTime { get; set; }
        [Column("endTime")]
        public int EndTime { get; set; }
        [Column("bufferTime")]
        public int BufferTime { get; set; }
        [Column("hideBranding")]
        public bool HideBranding { get; set; }
        [Column("theme")]
        public string? Theme { get; set; }
        [Column("created", TypeName = "timestamp(3) without time zone")]
        public Instant Created { get; set; }
        [Column("completedOnboarding")]
        public bool? CompletedOnboarding { get; set; }
        [Column("locale")]
        public string? Locale { get; set; }
        [Column("twoFactorSecret")]
        public string? TwoFactorSecret { get; set; }
        [Column("twoFactorEnabled")]
        public bool TwoFactorEnabled { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Availability> Availability { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Booking> Booking { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Credential> Credential { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Membership> Membership { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Schedule> Schedule { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<SelectedCalendar> SelectedCalendar { get; set; }
    }
}