// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NodaTime;

#nullable enable

namespace Workshop.Calendar.Api
{
    [Index(nameof(Identifier), nameof(Token), Name = "VerificationRequest.identifier_token_unique", IsUnique = true)]
    [Index(nameof(Token), Name = "VerificationRequest.token_unique", IsUnique = true)]
    public partial class VerificationRequest
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("identifier")]
        public string Identifier { get; set; } = default!;
        [Required]
        [Column("token")]
        public string Token { get; set; } = default!;
        [Column("expires", TypeName = "timestamp(3) without time zone")]
        public Instant Expires { get; set; }
        [Column("createdAt", TypeName = "timestamp(3) without time zone")]
        public Instant CreatedAt { get; set; }
        [Column("updatedAt", TypeName = "timestamp(3) without time zone")]
        public Instant UpdatedAt { get; set; }
    }
}