apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: linc-kafka-connect-cluster
  annotations:
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.1.0
  replicas: 1
  bootstrapServers: linc-kafka-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: linc-kafka-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
    topic.creation.enable: true
  build:
    output:
      type: docker
      image: mickdelaney/kafka-connect-debezium-pg:latest
      pushSecret: mickdelaney-dockerhub-credentials
    plugins: 
      - name: debezium-postgres-connector
        artifacts:
          - type: zip
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.8.1.Final/debezium-connector-postgres-1.8.1.Final-plugin.zip
  template:
    pod:
      imagePullSecrets:
        - name: mickdelaney-dockerhub-credentials