// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Workshop.Calendar.Api;

#nullable disable

namespace Workshop.Calendar.Api.Configurations
{
    public partial class BookingReferenceConfiguration : IEntityTypeConfiguration<BookingReference>
    {
        public void Configure(EntityTypeBuilder<BookingReference> entity)
        {
            entity.HasOne(d => d.Booking)
                .WithMany(p => p.BookingReference)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("BookingReference_bookingId_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BookingReference> entity);
    }
}
