// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Workshop.Calendar.Api;

#nullable disable

namespace Workshop.Calendar.Api.Configurations
{
    public partial class DailyEventReferenceConfiguration : IEntityTypeConfiguration<DailyEventReference>
    {
        public void Configure(EntityTypeBuilder<DailyEventReference> entity)
        {
            entity.Property(e => e.Dailytoken).HasDefaultValueSql("'dailytoken'::text");

            entity.Property(e => e.Dailyurl).HasDefaultValueSql("'dailycallurl'::text");

            entity.HasOne(d => d.Booking)
                .WithOne(p => p.DailyEventReference)
                .HasForeignKey<DailyEventReference>(d => d.BookingId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("DailyEventReference_bookingId_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DailyEventReference> entity);
    }
}
