// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Workshop.Calendar.Api;

#nullable disable

namespace Workshop.Calendar.Api.Configurations
{
    public partial class EventTypeConfiguration : IEntityTypeConfiguration<EventType>
    {
        public void Configure(EntityTypeBuilder<EventType> entity)
        {
            entity.Property(e => e.Currency).HasDefaultValueSql("'usd'::text");

            entity.Property(e => e.MinimumBookingNotice).HasDefaultValueSql("120");

            entity.Property(e => e.PeriodType).HasDefaultValueSql("'unlimited'::text");

            entity.HasOne(d => d.Team)
                .WithMany(p => p.EventType)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("EventType_teamId_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EventType> entity);
    }
}
