// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Workshop.Calendar.Api;

#nullable disable

namespace Workshop.Calendar.Api.Configurations
{
    public partial class EventTypeCustomInputConfiguration : IEntityTypeConfiguration<EventTypeCustomInput>
    {
        public void Configure(EntityTypeBuilder<EventTypeCustomInput> entity)
        {
            entity.Property(e => e.Placeholder).HasDefaultValueSql("''::text");

            entity.HasOne(d => d.EventType)
                .WithMany(p => p.EventTypeCustomInput)
                .HasForeignKey(d => d.EventTypeId)
                .HasConstraintName("EventTypeCustomInput_eventTypeId_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EventTypeCustomInput> entity);
    }
}
