// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Workshop.Calendar.Api;

#nullable disable

namespace Workshop.Calendar.Api.Configurations
{
    public partial class SelectedCalendarConfiguration : IEntityTypeConfiguration<SelectedCalendar>
    {
        public void Configure(EntityTypeBuilder<SelectedCalendar> entity)
        {
            entity.HasKey(e => new { e.UserId, e.Integration, e.ExternalId })
                .HasName("SelectedCalendar_pkey");

            entity.HasOne(d => d.User)
                .WithMany(p => p.SelectedCalendar)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("SelectedCalendar_userId_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SelectedCalendar> entity);
    }
}
