replicaCount: 1
persistence:
  enabled: true
  size: 60Gi
  deleteEnabled: true
  storageClass: local-path
  existingClaim: docker-registry-pv-claim

secrets:
  htpasswd: admin:$2y$05$PsV/k7vrhhfiH5dFyBVTWe/HoiHPR5Jxmy5H6v9fIHh9jSkVSbAbq