# tye application configuration file
# read all about it at https://github.com/dotnet/tye

name: workshop
services:
- name: accountsapi
  project: src/AccountsApi/AccountsApi.csproj
  bindings:
  - name: https
    port: 5700
    protocol: https
- name: contentapi
  project: src/ContentApi/ContentApi.csproj
  bindings:
  - name: https 
    port: 5701
    protocol: https
- name: gateway
  project: src/Gateway/Gateway.csproj
  bindings:
  - name: https 
    port: 5702
    protocol: https
- name: oidc
  project: src/OIDC/OIDC.csproj
  bindings:
  - name: https 
    port: 5703
    protocol: https
- name: proxy
  project: src/Proxy/Proxy.csproj
  bindings:
  - name: https 
    port: 5100
    protocol: https
- name: redis
  image: redis
  bindings:
  - containerPort: 6379
    connectionString: "${host}:${port}" 
- name: postgres
  image:  postgres
  env:
    - name: POSTGRES_PASSWORD
  value: "pass@word1"
  bindings:
    - containerPort: 5432
    connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:POSTGRES_PASSWORD};    